name: Update YML and Restart Server

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull code and Restart server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: prmers.alecmcgail.com
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          if [ -d "/home/ubuntu/PRMERS-plugins" ]; then
            cd /home/ubuntu/PRMERS-plugins
            git pull
          else
            cd /home/ubuntu
            git clone git@github.com:amcgail/discourse-PRMERS.git PRMERS-plugins
            cd PRMERS-plugins
          fi

          bash deploy/after_pull.sh