name: Configuring Nginx

on:
  workflow_dispatch:

jobs:
  configure-nginx:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Nginx
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: 34.210.63.57
        username: ec2-user
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/ec2-user/jen-shop
          git pull
          sudo ./nginx.conf.sh